# Services URL
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${env.PROFILE:mockserver}

# Logging configuration
logging:
  level:
    org:
      mfruizs: DEBUG
      springframework:
        cloud:
          openfeign:
            ribbon:
              FeignLoadBalancer: DEBUG
        web:
          client:
            RestTemplate: DEBUG

## HttpStat.us
serviceOne:
  name: service-one
  url: https://httpstat.us/
  paths:
    getInternalServerError: /([0-9]*)

## json-place-holder
serviceTwo:
  name: service-two
  url: https://jsonplaceholder.typicode.com
  paths:
    postCustomData: /posts

# Wiremock server configuration
wiremock:
  enabled: false