## HttpStat.us
serviceOne:
  url: http://${wiremock.host}:${wiremock.port}
  forwardServer: https://httpstat.us

## json-place-holder
serviceTwo:
  url: http://${wiremock.host}:${wiremock.port}
  forwardServer: https://jsonplaceholder.typicode.com


# Wiremock server configuration
wiremock:
  enabled: true
  mapping: /wiremock-proxy-services-domain/src/main/resources
  host: localhost
  port: 9090
  stubMaps:
    - name: serviceOne-get-mock
      method: GET
      urlPath: ${serviceOne.paths.urlPath}
      forwardServer: ${serviceOne.forwardServer}
    - name: serviceTwo-post-mock
      method: POST
      urlPath: ${serviceTwo.paths.urlPath}
      forwardServer: ${serviceTwo.forwardServer}
